# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCeShi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyCeShi

pod ‘MBProgressHUD’
pod ‘YYModel’
pod ‘YYCache’
pod ‘YYImage’
pod ‘YYWebImage’
pod ‘YYText’
pod ‘YYKeyboardManager’
pod ‘YYDispatchQueuePool’
pod ‘YYAsyncLayer’
pod ‘YYCategories’
pod ‘FMDB’
pod ‘AFNetworking’
pod ‘Masonry’

  target 'MyCeShiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCeShiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
